name: sanad_app
description: "Sanad App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # Style And Widgets
  cupertino_icons: ^1.0.9

  # App Controller And Helpers
  flutter_bloc: ^9.1.1
  easy_localization: ^3.0.8
  permission_handler: ^13.0.0
  flutter_intl_phone_field: ^0.0.7
  intl: ^0.20.2
  open_file: ^4.0.0
  url_launcher: ^6.3.2

  # Network
  dio: ^5.9.2
  dartz: ^0.10.1
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^7.1.1

  # Firebase
  firebase_messaging: ^16.2.2
  firebase_core: ^4.9.0

  # Utilities
  share_plus: ^13.2.0
  easy_date_timeline: ^2.0.9
  dropdown_button2: ^3.1.0
  pin_code_fields: ^9.4.0
  flutter_widget_from_html: ^0.17.2
  carousel_slider: ^5.1.2
  dots_indicator: ^4.0.1
  flutter_svg: ^2.3.0
  shared_preferences: ^2.5.5
  smooth_page_indicator: ^2.0.1
  image_picker: ^1.2.2
  image_cropper: ^12.2.1
  flutter_image_compress: ^2.4.0
  top_snackbar_flutter: ^3.3.0
  dotted_decoration: ^2.0.0
  lottie: ^3.5.1
  file_selector: ^1.1.0
  flutter_launcher_icons: ^0.14.4
  dotted_border: ^3.1.0
  dio_cookie_manager: ^3.4.0
  cookie_jar: ^4.0.9
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  image_gallery_saver_plus: ^5.1.1
  mobile_scanner: ^7.4.0
  geolocator: ^14.0.3
  ably_flutter: ^1.2.44
  timeago: ^3.7.1
  collection: ^1.19.1
  path_provider: ^2.1.6
  emoji_picker_flutter: ^4.5.3
  audioplayers: ^6.8.1
  flutter_linkify: ^6.0.0

  #Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/data/
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/lottie/coming_soon.json
    - assets/sounds/message_received.mp3
    - assets/sounds/message_send.mp3

